"""The client fold: item store, session-state store, and their
composition ``SessionFold`` (port of the TypeScript SDK's fold)."""

from __future__ import annotations

from .item_store import (
    Appended,
    BufferedForAbsentItem,
    DeltaApplyOutcome,
    IgnoredStaleRevision,
    Inserted,
    ItemApplyOutcome,
    ItemLike,
    ItemStore,
    Replaced,
    TerminalUnknownItemAnnotation,
)
from .session_fold import (
    SESSION_STATE_METHODS,
    LIVE_HOST_STATE_PROJECTIONS,
    LIVE_HOST_STATE_PROJECTIONS,
    VIEW_EVENT_METHODS,
    ApprovalPending,
    ApprovalResolvedFold,
    DeliveryGap,
    FoldItems,
    FoldOutcome,
    FoldSessionState,
    IgnoredMissingParams,
    IgnoredStaleFrame,
    IgnoredUnrecognizedMethod,
    ItemDeltaFold,
    ItemFold,
    PendingApproval,
    SessionFold,
    SessionStateFold,
    TurnEntry,
    TurnFold,
    TurnState,
    UserInputPending,
    UserInputSettledFold,
)
from .state_store import SessionStateStore, StateApplyOutcome, StateValue

__all__ = [
    "SESSION_STATE_METHODS",
    "LIVE_HOST_STATE_PROJECTIONS",
    "VIEW_EVENT_METHODS",
    "Appended",
    "ApprovalPending",
    "ApprovalResolvedFold",
    "BufferedForAbsentItem",
    "DeliveryGap",
    "DeltaApplyOutcome",
    "FoldItems",
    "FoldOutcome",
    "FoldSessionState",
    "IgnoredMissingParams",
    "IgnoredStaleFrame",
    "IgnoredStaleRevision",
    "IgnoredUnrecognizedMethod",
    "Inserted",
    "ItemApplyOutcome",
    "ItemDeltaFold",
    "ItemFold",
    "ItemLike",
    "ItemStore",
    "PendingApproval",
    "Replaced",
    "SessionFold",
    "SessionStateFold",
    "SessionStateStore",
    "StateApplyOutcome",
    "StateValue",
    "TerminalUnknownItemAnnotation",
    "TurnEntry",
    "TurnFold",
    "TurnState",
    "UserInputPending",
    "UserInputSettledFold",
]
