"""The charter test ``compatibility_row_generated_and_cited``.

The governing rule: the compatibility page's Python row has a TREE-DERIVABLE half —
supported Python versions, the stable-bundle schema fingerprint, the exact
pydantic pin — generated by the same extractor the docs build calls
(``--emit compatibility``), and the governing rule mismatch error CITES that
page. Two properties, each an arm:

* the emitted values equal independent reads of their sources of truth (the
  two package manifests and the stable-bundle manifest) — one derivation,
  never a restated copy;
* citation parity: ``muse_code.errors.COMPATIBILITY_PAGE_URL`` equals the
  site's own public identity plus the
  compatibility page's path, and that page actually carries the generated
  Python row (the ``PythonCompatibilityRow`` component).

The PER-WHEEL half (host version per published wheel) is release-cut
generated THROUGH THE PUBLISH PATH: ``scripts/sdk-py-wheel-rows.py``
derives each wheel's row — host version from the generated
``muse_code_msp.REQUIRED_HOST_VERSION``, fingerprint from the stable-bundle
manifest, wheel filename from the manifest's own name and version — and the
publish gate script runs it before anything could ship. Published rows
accumulate in ``clients/sdk-py/published-wheels.json`` (a bot-owned
generated artifact committed at publish integration, never hand-typed), the
extractor's compatibility emit carries them, and the page renders them. The
first owner-run publish (mirror workflow run 35056045080, 2026-09-16)
appended the 1.3.0 rows; the record is append-only, so a published wheel's
row must never disappear from it.
"""

from __future__ import annotations

import json
import re
import subprocess
import sys
from pathlib import Path
from typing import Any

try:
    import tomllib
except ModuleNotFoundError:  # Python 3.10: tomllib is 3.11+
    import tomli as tomllib  # type: ignore[no-redef]

PROJECT_ROOT = Path(__file__).resolve().parents[3]
EXTRACTOR = PROJECT_ROOT / "developer-docs" / "scripts" / "extract-python-reference.py"
DOCS_ROOT = PROJECT_ROOT / "developer-docs"

# A wall, not a budget: the emit is a sub-second manifest read (deadlock cap).
EXTRACT_WALL_SECONDS = 120


def _pyproject(package: str) -> dict[str, Any]:
    with (PROJECT_ROOT / "clients" / package / "pyproject.toml").open("rb") as handle:
        return tomllib.load(handle)


def _emitted_row() -> dict[str, Any]:
    result = subprocess.run(
        [sys.executable, str(EXTRACTOR), "--repo-root", str(PROJECT_ROOT), "--emit", "compatibility"],
        capture_output=True,
        text=True,
        timeout=EXTRACT_WALL_SECONDS,
        check=False,
    )
    assert result.returncode == 0, f"compatibility emit failed:\n{result.stderr}"
    row = json.loads(result.stdout)
    assert isinstance(row, dict)
    return row


def test_the_tree_derivable_half_derives_from_the_tree() -> None:
    row = _emitted_row()
    sdk = _pyproject("sdk-py")["project"]
    msp = _pyproject("msp-py")["project"]
    manifest = json.loads(
        (PROJECT_ROOT / "schema" / "msp" / "stable" / "manifest.json").read_text()
    )
    assert row["requiresPython"] == sdk["requires-python"] == msp["requires-python"]
    assert f"pydantic=={row['pydanticPin']}" in sdk["dependencies"]
    assert row["schemaFingerprint"] == manifest["fingerprint"]
    assert row["schemaVersionNumber"] == manifest["schemaVersion"]
    # Independent re-reads of the manifests' own names, never the same
    # literal twice (the review's hand-typed-twice finding).
    assert row["distributions"] == {
        msp["name"]: "muse_code_msp",
        sdk["name"]: "muse_code",
    }


def _site_constant(name: str) -> str:
    source = (DOCS_ROOT / "site-base.mjs").read_text()
    matched = re.search(rf'^export const {name} = "([^"]+)";$', source, re.MULTILINE)
    assert matched, f"site-base.mjs lost its {name} constant; update this parity arm"
    return matched.group(1)


def test_the_mismatch_error_citation_matches_the_page() -> None:
    sys.path.insert(0, str(PROJECT_ROOT / "clients" / "sdk-py" / "src"))
    try:
        from muse_code.errors import COMPATIBILITY_PAGE_URL
    finally:
        sys.path.pop(0)
    origin = _site_constant("SITE_ORIGIN")
    public_path = _site_constant("PUBLIC_PATH")
    assert COMPATIBILITY_PAGE_URL == f"{origin}{public_path}/compatibility/", (
        "the host-mismatch error cites a URL that is not the site's "
        "compatibility page"
    )
    page = (DOCS_ROOT / "src" / "content" / "docs" / "compatibility.mdx").read_text()
    assert "PythonCompatibilityRow" in page, (
        "the compatibility page lost its generated Python row"
    )
    assert "### Python" in page, "the compatibility page lost its Python section"


def _wheel_rows(*args: str) -> dict[str, Any]:
    result = subprocess.run(
        [
            sys.executable,
            str(PROJECT_ROOT / "scripts" / "sdk-py-wheel-rows.py"),
            "--repo-root",
            str(PROJECT_ROOT),
            *args,
        ],
        capture_output=True,
        text=True,
        timeout=EXTRACT_WALL_SECONDS,
        check=False,
    )
    assert result.returncode == 0, f"wheel-row emit failed:\n{result.stderr}"
    emitted = json.loads(result.stdout)
    assert isinstance(emitted, dict)
    return emitted


def test_the_per_wheel_rows_derive_from_the_tree() -> None:
    # The rule's release-cut half: the row a publish pairs with each wheel
    # is DERIVED — host version from the generated
    # muse_code_msp.REQUIRED_HOST_VERSION, fingerprint from the stable-bundle
    # manifest, wheel filename from the manifest's own name and version —
    # never hand-typed.
    emitted = _wheel_rows()
    sys.path.insert(0, str(PROJECT_ROOT / "clients" / "msp-py" / "src"))
    try:
        from muse_code_msp import REQUIRED_HOST_VERSION, SCHEMA_FINGERPRINT
    finally:
        sys.path.pop(0)
    assert emitted["schemaVersion"] == 1
    rows = emitted["wheels"]
    by_distribution = {row["distribution"]: row for row in rows}
    sdk = _pyproject("sdk-py")["project"]
    msp = _pyproject("msp-py")["project"]
    assert set(by_distribution) == {msp["name"], sdk["name"]}, (
        "both distributions publish together or neither does"
    )
    for project, import_name in ((msp, "muse_code_msp"), (sdk, "muse_code")):
        row = by_distribution[project["name"]]
        assert row["importName"] == import_name
        assert row["version"] == project["version"]
        normalized = re.sub(r"[-_.]+", "_", project["name"])
        assert row["wheel"] == f"{normalized}-{project['version']}-py3-none-any.whl"
        assert row["requiresPython"] == project["requires-python"]
        assert row["hostVersion"] == REQUIRED_HOST_VERSION
        assert row["schemaFingerprint"] == SCHEMA_FINGERPRINT


def _write_mirror_python_tree(root: Path) -> Path:
    # A mirror-layout python/ tree: the publish script resolves repo_root to
    # python/, which carries the clients but never the stable bundle (the
    # closure manifest scopes no schema path under python/).
    python_root = root / "python"
    package = python_root / "clients" / "msp-py" / "src" / "muse_code_msp"
    package.mkdir(parents=True)
    (package / "__init__.py").write_text(
        'REQUIRED_HOST_VERSION = "9.9.9"\nSCHEMA_FINGERPRINT = "sha256:abc"\n'
    )
    (python_root / "clients" / "msp-py" / "pyproject.toml").write_text(
        '[project]\nname = "muse-code-msp"\nversion = "9.9.9"\n'
        'requires-python = ">=3.10"\n'
    )
    (python_root / "clients" / "sdk-py").mkdir(parents=True)
    (python_root / "clients" / "sdk-py" / "pyproject.toml").write_text(
        '[project]\nname = "muse-code-sdk"\nversion = "9.9.9"\n'
        'requires-python = ">=3.10"\n'
    )
    return python_root


def _run_wheel_rows(repo_root: Path) -> "subprocess.CompletedProcess[str]":
    return subprocess.run(
        [
            sys.executable,
            str(PROJECT_ROOT / "scripts" / "sdk-py-wheel-rows.py"),
            "--repo-root",
            str(repo_root),
        ],
        capture_output=True,
        text=True,
        timeout=EXTRACT_WALL_SECONDS,
        check=False,
    )


def test_the_rows_resolve_the_stable_bundle_at_the_verbatim_layout(
    tmp_path: Path,
) -> None:
    # Mirror layout: repo_root is the mirror's python/ tree and the stable
    # bundle lives only at the verbatim sibling — the rows still derive.
    python_root = _write_mirror_python_tree(tmp_path)
    stable = tmp_path / "schema" / "msp" / "stable"
    stable.mkdir(parents=True)
    (stable / "manifest.json").write_text('{"fingerprint": "sha256:abc"}\n')
    result = _run_wheel_rows(python_root)
    assert result.returncode == 0, f"wheel-row emit failed:\n{result.stderr}"
    emitted = json.loads(result.stdout)
    assert [row["wheel"] for row in emitted["wheels"]] == [
        "muse_code_msp-9.9.9-py3-none-any.whl",
        "muse_code_sdk-9.9.9-py3-none-any.whl",
    ]
    assert {row["hostVersion"] for row in emitted["wheels"]} == {"9.9.9"}
    assert {row["schemaFingerprint"] for row in emitted["wheels"]} == {"sha256:abc"}


def test_the_rows_refuse_when_the_stable_bundle_is_missing_everywhere(
    tmp_path: Path,
) -> None:
    # Same fixture without the verbatim sibling: no stable bundle under
    # either layout refuses with the location, never a traceback.
    python_root = _write_mirror_python_tree(tmp_path)
    result = _run_wheel_rows(python_root)
    assert result.returncode != 0
    assert "stable-bundle manifest is missing" in result.stderr
    assert "Traceback" not in result.stderr


def test_the_published_wheels_record_rides_the_docs_build() -> None:
    # The accumulated record of published wheels is the committed
    # integration-time artifact the docs build reads: the compatibility emit
    # carries its rows verbatim, and the page component renders them (or the
    # explicit no-wheel-yet statement while it is empty). The record is
    # append-only: the first owner-run publish (permitted by the governing decision,
    # The publish record: mirror publish-pypi.yml run 35056045080, source commit
    # 94e98141a8074d50d2ac418de7acb5b16d8024fa, 2026-09-16) appended the
    # 1.3.0 rows, and a published wheel's row must never disappear or be
    # hand-edited afterwards — the row dicts below are the run's generated
    # output verbatim (scripts/sdk-py-wheel-rows.py), not hand-typed values.
    record = json.loads(
        (PROJECT_ROOT / "clients" / "sdk-py" / "published-wheels.json").read_text()
    )
    assert record["schemaVersion"] == 1
    published_1_3_0 = [
        {
            "distribution": "muse-code-msp",
            "importName": "muse_code_msp",
            "version": "1.3.0",
            "wheel": "muse_code_msp-1.3.0-py3-none-any.whl",
            "requiresPython": ">=3.10",
            "hostVersion": "1.3.0",
            "schemaFingerprint": "sha256:ab69549a7ebb423fce94068762da0b5ff3cdec1f8fc263dcc17248eda117f852",
        },
        {
            "distribution": "muse-code-sdk",
            "importName": "muse_code",
            "version": "1.3.0",
            "wheel": "muse_code_sdk-1.3.0-py3-none-any.whl",
            "requiresPython": ">=3.10",
            "hostVersion": "1.3.0",
            "schemaFingerprint": "sha256:ab69549a7ebb423fce94068762da0b5ff3cdec1f8fc263dcc17248eda117f852",
        },
    ]
    for row in published_1_3_0:
        assert row in record["wheels"], (
            f"the published {row['wheel']} lost its row: the record is "
            "append-only — rows are appended by the publish integration "
            "commit and never removed or hand-edited"
        )
    assert _emitted_row()["wheels"] == record["wheels"]
    component = (
        DOCS_ROOT / "src" / "components" / "PythonCompatibilityRow.astro"
    ).read_text()
    assert "row.wheels" in component, (
        "the compatibility page no longer renders the per-wheel rows; the "
        "first published wheel would ship without its row"
    )
